CREATE TABLE IF NOT EXISTS t_order_product_detail_data (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(255) NOT NULL,
    device_type VARCHAR(64),
    device_id VARCHAR(64),
    description TEXT,
    category_type VARCHAR(32),
    hardware_type VARCHAR(32),
    scene TEXT,
    device_count INT,
    income_month VARCHAR(32),
    currency VARCHAR(32),
    list_price DECIMAL(12,2),
    before_tier DECIMAL(12,2),
    before_price DECIMAL(12,2),
    discount_desc_before TEXT,
    after_tier DECIMAL(12,2),
    after_price DECIMAL(12,2),
    discount_desc_after TEXT,
    tier_increase DECIMAL(12,2),
    price_increase DECIMAL(12,2),
    after_tier_discount_rate DECIMAL(7,4),
    after_price_discount_rate DECIMAL(7,4),
    before_total_price DECIMAL(12,2),
    after_total_price DECIMAL(12,2),
    total_price_increase DECIMAL(12,2),
    total_increase_rate DECIMAL(7,4),
    addition_info TEXT,
    CONSTRAINT fk_detail_task FOREIGN KEY (task_id) REFERENCES t_profit_calculation_task(task_id) ON DELETE CASCADE,
    CONSTRAINT fk_detail_order FOREIGN KEY (task_id, order_id) REFERENCES t_order_info(task_id, order_id) ON DELETE CASCADE,
    KEY idx_detail_task (task_id),
    KEY idx_detail_order (task_id, order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
